version: '3.5'

services:
#    mysql:
#        image: mysql:5.7
#        container_name: nverine_mysql57
#        ports:
#            - "3306:3306"
#        volumes:
#            - mysql:/var/lib/mysql/
#        environment:
#            MYSQL_DATABASE: '${DB_NAME}'
#            MYSQL_USER: '${DB_USER}'
#            MYSQL_ROOT_PASSWORD: '${DB_PASS}'
#        networks:
#            - symfony
#
#    phpmyadmin:
#        container_name: nverine_phpmyadmin
#        image: phpmyadmin/phpmyadmin:latest
#        ports:
#            - 8081:80
#        environment:
#            - PMA_ARBITRARY=1
#        depends_on:
#            - mysql
#        networks:
#            - symfony

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: "America/Sao_Paulo"
                DB_HOST: "${DB_HOST}"
                DB_USER: "${DB_USER}"
                DB_PASS: "${DB_PASS}"
                DB_NAME: "${DB_NAME}"
                APP: "symfony"
                REP: "https://github.com/NVerine/symfony.git"
                ENVIRONMENT: "${ENVIRONMENT}"
                AZURE_STORAGE_CONNECTION_STRING: "${STORAGE}"
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
#        depends_on:
#            - mysql

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8080:80
        networks:
            - symfony
        depends_on:
            - php

volumes:
    mysql:

networks:
    symfony:
